### ISSUE TITLE
Adding a CAS wire to the  EDGE connector instead of removing RF modulator ?

### ISSUE THREAD

**Issue by amidarius** [c0pperdragon/ZX-Spectrum-Component-Video#2]
Please correct me if i'm wrong but, 
simple modificiation, adding a wire from CAS/Write (If this is ULA -> 4116 write? ) "test points" to the unused/NC pins on the EDGE connector (Component side 4/28) and You do not need to remove RF modulator anymore from the Spectrum. All other signals are already there, so this could be just an another expansion card to the ZX Spectrum 16/48K !
Data bus is already shared between 4116 an the rest of the computer so it is already available at the EDGE connector.

**Comment by c0pperdragon** [comment]
Indeed, I have to correct you. This machine actually has two seperate data bussses that are coupled together with resistors. As long as the CPU does not need to access the video RAM, it can work with its dedicated RAM and ROM independently of the ULA. Only when accessing the video RAM, the ULA forwards this requests to its own part of the system, or blocks the CPU altogether until it is done with RAM access itself.

The pins that are accessible on the edge connector carry the CPUs addresses and data. The data that is pulled by the ULA from the video RAM normally does not reach the CPU bus at all and in consequence  can not be sniffed from the edge connector.

**Comment by amidarius** [comment]
Yes, that's the way it works. 
Just consulted ZX Spectrum 48K Issue 2 schematic and Chris Smith's ULA Bible, 'The Spectrum ULA - How to Design A Microcomputer' and everything is crystal clear again, after 35 years ! :-)
It seems that 'socketed ULA' :-) if it's somehow there, the easiest solution if You do not want to solder anything. My Spectrum is already inside very big mechanical keyboard, so, space is not a problem and the solution is reversible with additional simple PCB.
Anyway, is it possible to connect this board without removing RF modulator when, like in my case, space is not a problem ? It should be.

**Comment by c0pperdragon** [comment]
Of course there is absolutely no need to remove the RF modulator if you have enough space to place the mod board somewhere else. Just find suitable points to pick off the GND and +5V from the main board and feed the supply into one of the GND connector pins of the mod board and its JPOWER1 pin respectively.

I did not mention this because I actually did not think of the possibility. Indeed when I think about it, a ZX Spectrum+  would actually have the necessary space inside its larger case. Other models of the ZX Spectrum would not need this specifc mod anyway, because they natively output some form of RGB.
