### ISSUE TITLE
RGBtoHDMI profile

### ISSUE THREAD

**Issue by IanSB** [c0pperdragon/ZX-Spectrum-Component-Video#3]
What are the default YUV levels for the ouput of this mod?

**Comment by c0pperdragon** [comment]
YPbPr is not well suited to work with the RGBtoHDMI because the Ys are too close together. Set jumper J3 to get RGsB output. There all color components are either 0, 1 or 0.5 (not quite, but close enough)

**Comment by IanSB** [comment]
I wonder if it would be possible to implement the functionality of this mod in the RGBtoHDMI CPLD (or a combination of the CPLD and software) as there are now 14 bits available on the CPLD inputs (12 RGB + HS & VS) which is more than enough to pick up the required signals, especially if it could be connected externally as suggested in https://github.com/c0pperdragon/ZX-Spectrum-Component-Video/issues/2

**Comment by c0pperdragon** [comment]
Unluckily the data signals by which the ULA communicates with the video RAM are _not_ available on the  edge connector (please see my reply to this topic).
The only way to do something similar via the edge connector is to sniff all address and data bits and memorize what the CPU writes into the video RAM. Could be possible, but requires far more signals.
Also the edge connector is in so much use for other purposes already.

**Comment by IanSB** [comment]
>The only way to do something similar via the edge connector is to sniff all address and data bits and memorize what the CPU writes into the video RAM. Could be possible, but requires far more signals.

Yes, I think there are a couple of other solutions that work that way, one of which also uses a CPLD and a Pi zero.

Still, it might be worth investigating an internal pickup solution like my current Atari / Amiga options. I think the CPLD would only be able to latch the data bus and control bits at the appropriate time and pass them to the Pi for a purely software emulation of the Spectrum's colour attribute based frame buffer. Something to look at one day.

Have you tried creating a profile for your Spectrum board yet?

**Comment by c0pperdragon** [comment]
I didn't put any attention on the Spectrum yet  I basically hoped, you would take care of that 😉

Going digital directly is of course also an option. Maybe the space inside the original Speccy is a bit too restricted. Using a CPLD you could directly replace the whole ULA and produce a 4-bit video signal like later versions of the Spectrum did. This could then allow a unified RGBtoHDMI solution.

**Comment by patters-match** [comment]
Is it possible to take your design a little further and actually output HDMI (via a micro HDMI connector, which would also avoid modding the case)? The issue these days is that the latest TVs don't even have component inputs. Having spent the "lockdown" period researching and buying various HDMI solutions for my various retro consoles, the Spectrum is still a system I can only use on an older TV.
My (admittedly limited) understanding of this is that once you have YPbPr, it's actually fairly straightforward digitally encode that colourspace to HDMI, and RGB isn't really necessary - especially since the ULA is limited to generating luma and chroma in the first place.
Or do you need a more complex FPGA to handle that analogue to digital conversion?

**Comment by IanSB** [comment]
Profile now available in beta 54 of RGBtoHDMI
